/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'heel.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./heel.android-arm64.node')
          } else {
            nativeBinding = require('heel-sandbox-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'heel.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./heel.android-arm-eabi.node')
          } else {
            nativeBinding = require('heel-sandbox-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'heel.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./heel.win32-x64-msvc.node')
          } else {
            nativeBinding = require('heel-sandbox-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'heel.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./heel.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('heel-sandbox-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'heel.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./heel.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('heel-sandbox-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'heel.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./heel.darwin-universal.node')
      } else {
        nativeBinding = require('heel-sandbox-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'heel.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./heel.darwin-x64.node')
          } else {
            nativeBinding = require('heel-sandbox-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'heel.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./heel.darwin-arm64.node')
          } else {
            nativeBinding = require('heel-sandbox-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'heel.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./heel.freebsd-x64.node')
      } else {
        nativeBinding = require('heel-sandbox-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'heel.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./heel.linux-x64-musl.node')
            } else {
              nativeBinding = require('heel-sandbox-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'heel.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./heel.linux-x64-gnu.node')
            } else {
              nativeBinding = require('heel-sandbox-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'heel.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./heel.linux-arm64-musl.node')
            } else {
              nativeBinding = require('heel-sandbox-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'heel.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./heel.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('heel-sandbox-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'heel.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./heel.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('heel-sandbox-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'heel.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./heel.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('heel-sandbox-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'heel.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./heel.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('heel-sandbox-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'heel.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./heel.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('heel-sandbox-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'heel.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./heel.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('heel-sandbox-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { ChildProcessJs, StdioConfigJs, Command, presetStrict, presetPythonDev, presetPythonDataScience, IpcRouterJs, createIpcRouter, Sandbox, createSandbox, securityConfigStrict, securityConfigPermissive } = nativeBinding

module.exports.ChildProcessJs = ChildProcessJs
module.exports.StdioConfigJs = StdioConfigJs
module.exports.Command = Command
module.exports.presetStrict = presetStrict
module.exports.presetPythonDev = presetPythonDev
module.exports.presetPythonDataScience = presetPythonDataScience
module.exports.IpcRouterJs = IpcRouterJs
module.exports.createIpcRouter = createIpcRouter
module.exports.Sandbox = Sandbox
module.exports.createSandbox = createSandbox
module.exports.securityConfigStrict = securityConfigStrict
module.exports.securityConfigPermissive = securityConfigPermissive
