/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Standard I/O configuration */
export const enum StdioConfigJs {
  /** Inherit from parent process */
  Inherit = 'Inherit',
  /** Create a new pipe */
  Piped = 'Piped',
  /** Redirect to null */
  Null = 'Null'
}
/** How a process exited. */
export interface ExitStatusJs {
  /** Whether the process exited with a success status. */
  success: boolean
  /** The exit code, or `null` when a signal ended the process. */
  code?: number
}
/** A finished process and everything it wrote. */
export interface ProcessOutputJs {
  /** How the process exited. */
  status: ExitStatusJs
  /** Everything the process wrote to standard output. */
  stdout: Buffer
  /** Everything the process wrote to standard error. */
  stderr: Buffer
}
/** Resource limits for sandboxed processes. */
export interface ResourceLimitsJs {
  /** Maximum address space, in bytes. */
  maxMemoryBytes?: number
  /** Maximum CPU time, in seconds. */
  maxCpuTimeSecs?: number
  /** Maximum size of a file the process may create, in bytes. */
  maxFileSizeBytes?: number
  /** Maximum number of processes. */
  maxProcesses?: number
}
/** How much of the host the sandbox can see. */
export const enum IsolationJs {
  /** Only the working directory is readable or writable. */
  Strict = 'Strict',
  /** The working directory is writable; the rest of the system is readable. */
  Default = 'Default',
  /** The whole filesystem is readable and writable. */
  Permissive = 'Permissive'
}
/** Sandbox configuration. */
export interface SandboxConfigJs {
  /** Network policy; defaults to denying everything. */
  network?: NetworkPolicyConfig
  /** Isolation level; defaults to `default`. */
  isolation?: IsolationJs
  /** Security toggles layered onto the isolation level's preset. */
  security?: SecurityConfigJs
  /** Paths the sandbox may write. */
  writablePaths?: Array<string>
  /** Paths the sandbox may read. */
  readablePaths?: Array<string>
  /** Paths the sandbox may execute. */
  executablePaths?: Array<string>
  /** Python configuration. */
  python?: PythonConfigJs
  /** Working directory; generated when omitted. */
  workingDir?: string
  /** Host environment variables to forward. */
  envPassthrough?: Array<string>
  /** Resource limits. */
  limits?: ResourceLimitsJs
}
/** A sandbox that exposes only its own working directory, with no network. */
export declare function presetStrict(): SandboxConfigJs
/** A sandbox for Python development, with writes to the virtual environment. */
export declare function presetPythonDev(): SandboxConfigJs
/** A sandbox for Python data science, with the usual toolchain preinstalled. */
export declare function presetPythonDataScience(): SandboxConfigJs
/** Network policy configuration. */
export interface NetworkPolicyConfig {
  /** Policy type: `deny-all`, `allow-all`, or `allow-list`. */
  policyType: string
  /** Domains for the allow-list policy; supports `*.example.com`. */
  domains?: Array<string>
}
/** Virtual environment configuration. */
export interface VenvConfigJs {
  /** Where the environment lives. */
  path?: string
  /** Interpreter used to create the environment. */
  python?: string
  /** Packages to install. */
  packages?: Array<string>
  /** Expose the system's site-packages. */
  systemSitePackages?: boolean
  /** Tool used to create the environment: `auto`, `uv`, or `python`. */
  backend?: string
}
/** Python configuration. */
export interface PythonConfigJs {
  /** Virtual environment configuration. */
  venv?: VenvConfigJs
  /** Let the sandboxed process write to the virtual environment. */
  allowPipInstall?: boolean
}
/**
 * Create a sandbox.
 *
 * @example
 * ```typescript
 * import { createSandbox } from 'heel-sandbox';
 *
 * const sandbox = await createSandbox();
 * const output = await sandbox.command('/bin/echo').arg('hello').output();
 * console.log(output.stdout.toString()); // "hello
"
 * ```
 */
export declare function createSandbox(config?: SandboxConfigJs | undefined | null): Promise<Sandbox>
/**
 * A partial set of security toggles, layered onto the strict preset.
 *
 * Every field is optional: omitting one keeps the preset's value.
 */
export interface SecurityConfigJs {
  /** Protect user home directories. */
  protectUserHome?: boolean
  /** Let macOS prompt for TCC-protected folders instead of denying them. */
  allowTccPrompts?: boolean
  /** Protect SSH and GPG credentials. */
  protectCredentials?: boolean
  /** Protect cloud provider configuration. */
  protectCloudConfig?: boolean
  /** Protect browser data. */
  protectBrowserData?: boolean
  /** Protect the system keychain. */
  protectKeychain?: boolean
  /** Protect shell history. */
  protectShellHistory?: boolean
  /** Protect package manager credentials. */
  protectPackageCredentials?: boolean
  /** Allow GPU access. */
  allowGpu?: boolean
  /** Allow NPU / Neural Engine access. */
  allowNpu?: boolean
  /** Allow general hardware access. */
  allowHardware?: boolean
}
/** The strict security preset, with every protection enabled. */
export declare function securityConfigStrict(): SecurityConfigJs
/** The interactive preset: strict, but macOS may prompt for protected folders. */
export declare function securityConfigInteractive(): SecurityConfigJs
/** The permissive security preset. */
export declare function securityConfigPermissive(): SecurityConfigJs
/** A spawned child process in the sandbox */
export declare class ChildProcessJs {
  /** Get the process ID */
  get pid(): number
  /** Wait for the process to exit */
  wait(): Promise<ExitStatusJs>
  /** Wait for the process to exit and collect all output */
  waitWithOutput(): Promise<ProcessOutputJs>
  /** Kill the process */
  kill(): Promise<void>
  /** Check if the process has exited without blocking */
  tryWait(): Promise<ExitStatusJs | null>
  /** Write data to the process stdin */
  writeStdin(data: Buffer): Promise<void>
  /** Read available data from stdout (non-blocking) */
  readStdout(maxBytes: number): Promise<Buffer>
  /** Read available data from stderr (non-blocking) */
  readStderr(maxBytes: number): Promise<Buffer>
}
/** Command builder for executing programs in the sandbox */
export declare class Command {
  /** Add a single argument */
  arg(value: string): this
  /** Add multiple arguments */
  args(values: Array<string>): this
  /** Set an environment variable */
  env(key: string, value: string): this
  /** Set multiple environment variables */
  envs(vars: Array<Array<string>>): this
  /** Set the working directory */
  cwd(dir: string): this
  /** Configure stdin */
  stdin(config: StdioConfigJs): this
  /** Configure stdout */
  stdout(config: StdioConfigJs): this
  /** Configure stderr */
  stderr(config: StdioConfigJs): this
  /** Run the command and collect all output */
  output(): Promise<ProcessOutputJs>
  /** Run the command and return only exit status */
  status(): Promise<ExitStatusJs>
  /** Spawn the command as a child process */
  spawn(): Promise<ChildProcessJs>
}
/**
 * A sandbox for running untrusted code with restricted permissions.
 *
 * When disposed, the sandbox stops its proxy, kills the processes it spawned,
 * and removes a generated working directory.
 */
export declare class Sandbox {
  /** Create a sandbox. */
  static create(config?: SandboxConfigJs | undefined | null): Promise<Sandbox>
  /** The working directory path. */
  get workingDir(): string
  /** The proxy URL, or `null` when network access is denied. */
  get proxyUrl(): string | null
  /** Build a command to run in the sandbox. */
  command(program: string): Command
  /** Run a Python script in the sandbox. */
  runPython(script: string): Promise<ProcessOutputJs>
  /** Keep the working directory after the sandbox is disposed. */
  keepWorkingDir(): Promise<void>
  /** Dispose the sandbox, releasing everything it holds. */
  dispose(): Promise<void>
}
